### ISSUE TITLE
MapleSeed has Stopped working

### ISSUE THREAD

**Issue by Tonyhk47** [Tsume/Maple-Tree#33]
Getting this on load up of version 2.1.1.10.

https://pastebin.com/1jGTpxXd

**Comment by Tsume** [comment]
Try this out, and let me know how it goes. The null reference should be fixed.

https://pixxy.in/04I2262.zip

**Comment by Tonyhk47** [comment]
still getting an error, seems to be null reference still.

https://pastebin.com/C3s2VjrY

**Comment by Tsume** [comment]
I was able to track down another null reference.

https://pixxy.in/KVz2263.zip

**Comment by Tonyhk47** [comment]
Still the same result, next error log.

https://pastebin.com/iP6xe8nn

**Comment by Tsume** [comment]
Sometimes I think I can't read.

It's crashing because of "at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)"
I was completely overlooking it. I'll be surprised if this one doesn't work.

https://pixxy.in/J058265.rar

**Comment by Tonyhk47** [comment]
same result =/

https://pastebin.com/uSCumemr

**Comment by Rehtard** [comment]
Hey I'm getting the same errors. With the last update you posted I got this error:
https://pastebin.com/h8VvL6cm

**Comment by Tsume** [comment]
Finally an exact error I can trace. Now we're getting somewhere.

https://pixxy.in/AmC8266.rar

**Comment by Tonyhk47** [comment]
no error from that =]

**Comment by Neonzzy** [comment]
Thankss <3 I was with the same error

**Comment by Tsume** [comment]
What's rather strange though, is that GraphicPack seems to be initialing null, which it shouldn't.

Let me know if that feature doesn't work. I'll look into it.

**Comment by Rehtard** [comment]
Thanks for the very quick fix :D Keep up the good work :D

**Comment by Tonyhk47** [comment]
It seems graphics packs are not currently working on cemu

**Comment by Tsume** [comment]
Make sure you enable them after launching Cemu. You'll have to do that for every title and GP, annoying, but there's no way around it without hi-jacking your mouse and keyboard lol.

**Comment by Tonyhk47** [comment]
I believe I am, I'm activating them in the options menu of cemu, but I'm seeing no results

**Comment by Tsume** [comment]
Go to Control Panel and make sure Graphic Packs is enabled.
