### ISSUE TITLE
Problem with loading Mapleseed and update/dlc errors

### ISSUE THREAD

**Issue by himynameisnate** [Tsume/Maple-Tree#47]
I've been getting this error whenever I try loading up Mapleseed:

![image](https://cloud.githubusercontent.com/assets/27875577/25300479/a8bcf7a8-2753-11e7-897b-977ca01c0a77.png)

And whenever I would try to add DLC or Update a game, this would pop up:

![image](https://cloud.githubusercontent.com/assets/27875577/25300492/de0fc098-2753-11e7-9390-c41fcb37b4b8.png)

I tried uninstalling Mapleseed, restarting my pc, fix registry errors on CCleaner, all to no avail. Help would be appreciated. Thanks.

**Comment by Tsume** [comment]
I'll be looking into this bug today and will update you with a possible fix later.

**Comment by Tsume** [comment]
Oh, btw this is happening due to content not being found for a title ID. Which game and ID are you using?

**Comment by himynameisnate** [comment]
The error is popping up for all the games that I tried to update or
download dlc.

It was working fine before, but it only started happening after I
downloaded Twilight Princess HD[USA]. I tried to run the game on Cemu, but
it crashed so I ended up deleting it, thought it didn't work (only later to
find that I needed to transfer the Code and Meta folders from the sav
folders). Could this be the cause? I haven't deleted the folder that
downloaded into the save folder.

I'm not on my PC right now, this is just off the top of my head.

**Comment by elunty** [comment]
Here is another error that can happen if there is no data for for a title (tried updating mario 3d world) 

![capture](https://cloud.githubusercontent.com/assets/1414366/25309358/6059902c-2788-11e7-999b-fb08377d4703.PNG)

**Comment by Tsume** [comment]
There are no updates for 3d mario world as far as I'm aware. Being able to select update for that title is likely a bug. I'll look more into it later.

**Comment by Tsume** [comment]
If you still need help, feel free to update this thread.

**Comment by Tsume** [comment]
- [ ] Check for non-existent content

**Comment by elunty** [comment]
If you are adding this issue to your checklist, might as well add the functionality that will check if you are already up to date before downloaded the lastest update/dlc anyways (no need to force downloading the update if you already have the newest version)

**Comment by Tsume** [comment]
The above issue about missing content has been fixed for version 2.1.1.13+
Going forward you shouldn't see update buttons for title without updates.

Latest title version checks will be added to another update. It's being tracked in another open issue.

**Comment by n1ckn4m3** [comment]
Still getting this behavior on 2.1.1.14:

The following update attempts crash due to the following:

> System.NullReferenceException: Could not locate content for title ID xxxxxxxxxxxxxxxx
   at MapleCake.Models.MapleButtons.<DownloadContentClick>d__32.MoveNext()

* Batman Arkham Origins Blackgate Edition v0 -> v16 update
* Bayonetta v0 -> v1 update

Additionally, the following games still allow selection of [+] Update even though there is no released update:

* Disney Epic Mickey 2 The Power of Two
* Game & Wario
* LEGO City Undercover

The only unifying thing I can determine is that all of those game titles have extended characters in them (trademark symbols, registered symbols, colons).  I'm sure there are more, but those are the only ones I have available.  They were all extracted from WUDs/WUXs I ripped personally from discs I own, I don't know if that changes how MapleTree works vs. having downloaded them through one of the eShop downloaders.

Otherwise, awesome work, your app is easily the most convenient way to manage DLC/Updates!
